export const projectData = [
    {
        name: "Save Your Food (Web)",
        description: "A food sustainability website, where you can manage and track your pantry, grocery lists, and weekly meal plans.",
        techUsed: ["React", "Bootstrap", "Java", "SpringBoot", "PostgreSQL", "SQL"],
        otherTechUsed: ["RESTful Routing", "JSON API", "GitHub"],
        img: './foodApp.png',
        liveLink: 'https://food-app-frontend.netlify.app/',
        githubFrontEnd: 'https://github.com/dmlacerte/food-app-frontend',
        githubBackEnd: 'https://github.com/dmlacerte/food-app-backend',
    },
    {
        name: "Save Your Food (Mobile)",
        description: "A food sustainability mobile app, where you can manage and track your pantry, grocery lists, and weekly meal plans.",
        techUsed: ["React Native", "Java", "SpringBoot", "PostgreSQL", "SQL"],
        otherTechUsed: ["RESTful Routing", "JSON API", "GitHub"],
        img: './foodAppMobile.gif',
        githubFrontEnd: 'https://github.com/dmlacerte/food-app-frontend-mobile',
        githubBackEnd: 'https://github.com/dmlacerte/food-app-backend',
    },
    {
        name: "Pretty Good Reads",
        description: "A spin off of Good Reads, where users can view books, add them to category lists, and add and view user reviews.",
        techUsed: ["React", "HTML", "CSS", "JavaScript", "Express & Node.js", "MongoDB"],
        otherTechUsed: ["RESTful Routing", "JSON API", "GitHub"],
        img: './readingApp.gif',
        liveLink: 'https://pretty-good-reads.netlify.app/',
        githubFrontEnd: 'https://github.com/dmlacerte/pretty-good-reads-frontend',
        githubBackEnd: 'https://github.com/dmlacerte/pretty-good-reads-backend',
    },
    {
        name: "USA Travel App",
        description: "A trip management website, where you can plan and record your travels around the U.S. (restaurants, hotels, entertainment, etc.).",
        techUsed: ["HTML", "CSS", "JavaScript", "Bootstrap", "Express & Node.js", "MongoDB"],
        otherTechUsed: ["RESTful Routing", "JSON API", "GitHub"],
        img: './travelApp.gif',
        liveLink: 'https://dml-mytravelapp.herokuapp.com/',
        githubFullStack: 'https://github.com/dmlacerte/Travel-App',
    },
    {
        name: "Battleship",
        description: "Interactive Battleship board using DOM manipulation and class construction, allowing the player to set their boards and make moves.",
        techUsed: ["HTML", "CSS", "JavaScript"],
        otherTechUsed: ["GitHub"],
        img: './battleship.gif',
        liveLink: 'https://dmlacerte.github.io/Battleship/',
        githubFrontEnd: 'https://github.com/dmlacerte/Battleship',
    }
];