export const projectData = [
    {
        name: "Save Your Food (Web)",
        description: "A food sustainability website, where you can manage and track your pantry, grocery lists, and weekly meal plans.",
        techUsed: ["Java", "SpringBoot", "PostgreSQL", "React", "React Native", "JavaScript", "SQL", "Bootstrap", "RESTful Routing", "JSON API", "GitHub"],
        img: './foodApp.png',
        liveLink: '',
        githubFrontEnd: '',
        githubBackEnd: '',
    },
    {
        name: "Save Your Food (Mobile)",
        description: "A food sustainability mobile app, where you can manage and track your pantry, grocery lists, and weekly meal plans.",
        techUsed: ["Java", "SpringBoot", "PostgreSQL", "React Native", "JavaScript", "SQL", "RESTful Routing", "JSON API", "GitHub"],
        img: './foodAppMobile.gif',
        liveLink: '',
        githubFrontEnd: '',
        githubBackEnd: '',
    },
    {
        name: "Pretty Good Reads",
        description: "A spin off of Good Reads, where users can view books, add them to category lists, and add and view user reviews.",
        techUsed: ["MongoDB", "Express & Node.js", "HTML", "CSS", "JavaScript", "React", "RESTful Routing", "JSON API", "GitHub"],
        img: './readingApp.gif',
        liveLink: '',
        githubFrontEnd: '',
        githubBackEnd: '',
    },
    {
        name: "USA Travel App",
        description: "A trip management website, where you can plan and record your travels around the U.S. (restaurants, hotels, entertainment, etc.).",
        techUsed: ["MongoDB", "Express & Node.js", "HTML", "CSS", "JavaScript", "Bootstrap", "RESTful Routing", "JSON API", "GitHub"],
        img: './travelApp.gif',
        liveLink: '',
        githubFrontEnd: '',
        githubBackEnd: '',
    },
    {
        name: "Battleship",
        description: "Interactive Battleship board using DOM manipulation and class construction, allowing the player to set their boards and make moves.",
        techUsed: ["HTML", "CSS", "JavaScript", "GitHub"],
        img: './battleship.gif',
        liveLink: '',
        githubFrontEnd: '',
        githubBackEnd: '',
    }
];